/*
 * WalletsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "closed", skip_serializing_if = "Option::is_none")]
    pub closed: Option<bool>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "userId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "priceListId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_list_id: Option<Option<String>>,
    #[serde(rename = "enrollmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enrollment_id: Option<Option<String>>,
    #[serde(rename = "individualId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub individual_id: Option<Option<String>>,
    #[serde(rename = "organizationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<Option<String>>,
    #[serde(rename = "receiverTenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receiver_tenant_id: Option<Option<String>>,
    #[serde(rename = "firstName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<Option<String>>,
    #[serde(rename = "lastName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<Option<String>>,
    #[serde(rename = "companyName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<Option<String>>,
    #[serde(rename = "billingEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billing_email: Option<Option<String>>,
    #[serde(rename = "addressLine1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address_line1: Option<Option<String>>,
    #[serde(rename = "addressLine2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address_line2: Option<Option<String>>,
    #[serde(rename = "postalCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Option<String>>,
    #[serde(rename = "countryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_id: Option<Option<String>>,
    #[serde(rename = "stateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<Option<String>>,
    #[serde(rename = "cityId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city_id: Option<Option<String>>,
    #[serde(rename = "customerNotes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_notes: Option<Option<String>>,
    #[serde(rename = "taxCalculationMethod", skip_serializing_if = "Option::is_none")]
    pub tax_calculation_method: Option<TaxCalculationMethod>,
    #[serde(rename = "forexRate", skip_serializing_if = "Option::is_none")]
    pub forex_rate: Option<f64>,
    #[serde(rename = "currencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Option<String>>,
    #[serde(rename = "totalDetail", skip_serializing_if = "Option::is_none")]
    pub total_detail: Option<f64>,
    #[serde(rename = "totalDetailCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_detail_currency_id: Option<Option<String>>,
    #[serde(rename = "totalProfit", skip_serializing_if = "Option::is_none")]
    pub total_profit: Option<f64>,
    #[serde(rename = "totalProfitCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_profit_currency_id: Option<Option<String>>,
    #[serde(rename = "totalDiscounts", skip_serializing_if = "Option::is_none")]
    pub total_discounts: Option<f64>,
    #[serde(rename = "totalDiscountsCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_discounts_currency_id: Option<Option<String>>,
    #[serde(rename = "totalSurcharges", skip_serializing_if = "Option::is_none")]
    pub total_surcharges: Option<f64>,
    #[serde(rename = "totalSurchargesCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_surcharges_currency_id: Option<Option<String>>,
    #[serde(rename = "totalTaxBase", skip_serializing_if = "Option::is_none")]
    pub total_tax_base: Option<f64>,
    #[serde(rename = "totalTaxBaseCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_tax_base_currency_id: Option<Option<String>>,
    #[serde(rename = "totalTaxes", skip_serializing_if = "Option::is_none")]
    pub total_taxes: Option<f64>,
    #[serde(rename = "totalTaxesCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_taxes_currency_id: Option<Option<String>>,
    #[serde(rename = "totalShippingCost", skip_serializing_if = "Option::is_none")]
    pub total_shipping_cost: Option<f64>,
    #[serde(rename = "totalShippingCostCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_shipping_cost_currency_id: Option<Option<String>>,
    #[serde(rename = "totalShippingTax", skip_serializing_if = "Option::is_none")]
    pub total_shipping_tax: Option<f64>,
    #[serde(rename = "totalShippingTaxCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_shipping_tax_currency_id: Option<Option<String>>,
    #[serde(rename = "totalWithheldTax", skip_serializing_if = "Option::is_none")]
    pub total_withheld_tax: Option<f64>,
    #[serde(rename = "totalWithheldTaxCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_withheld_tax_currency_id: Option<Option<String>>,
    #[serde(rename = "totalGlobalDiscounts", skip_serializing_if = "Option::is_none")]
    pub total_global_discounts: Option<f64>,
    #[serde(rename = "totalGlobalDiscountsCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_global_discounts_currency_id: Option<Option<String>>,
    #[serde(rename = "totalGlobalSurcharges", skip_serializing_if = "Option::is_none")]
    pub total_global_surcharges: Option<f64>,
    #[serde(rename = "totalGlobalSurchargesCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_global_surcharges_currency_id: Option<Option<String>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(rename = "totalCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_currency_id: Option<Option<String>>,
    #[serde(rename = "totalDetailInUsd", skip_serializing_if = "Option::is_none")]
    pub total_detail_in_usd: Option<f64>,
    #[serde(rename = "totalProfitInUsd", skip_serializing_if = "Option::is_none")]
    pub total_profit_in_usd: Option<f64>,
    #[serde(rename = "totalDiscountsInUsd", skip_serializing_if = "Option::is_none")]
    pub total_discounts_in_usd: Option<f64>,
    #[serde(rename = "totalSurchargesInUsd", skip_serializing_if = "Option::is_none")]
    pub total_surcharges_in_usd: Option<f64>,
    #[serde(rename = "totalTaxBaseInUsd", skip_serializing_if = "Option::is_none")]
    pub total_tax_base_in_usd: Option<f64>,
    #[serde(rename = "totalTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub total_taxes_in_usd: Option<f64>,
    #[serde(rename = "totalWithheldTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub total_withheld_taxes_in_usd: Option<f64>,
    #[serde(rename = "totalShippingCostInUsd", skip_serializing_if = "Option::is_none")]
    pub total_shipping_cost_in_usd: Option<f64>,
    #[serde(rename = "totalShippingTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub total_shipping_taxes_in_usd: Option<f64>,
    #[serde(rename = "totalGlobalDiscountsInUsd", skip_serializing_if = "Option::is_none")]
    pub total_global_discounts_in_usd: Option<f64>,
    #[serde(rename = "totalGlobalSurchargesInUsd", skip_serializing_if = "Option::is_none")]
    pub total_global_surcharges_in_usd: Option<f64>,
    #[serde(rename = "totalInUsd", skip_serializing_if = "Option::is_none")]
    pub total_in_usd: Option<f64>,
    #[serde(rename = "orderLinesCount", skip_serializing_if = "Option::is_none")]
    pub order_lines_count: Option<i32>,
    #[serde(rename = "quoteId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<Option<String>>,
    #[serde(rename = "walletId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<Option<String>>,
    #[serde(rename = "paymentTermId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_term_id: Option<Option<String>>,
    #[serde(rename = "parentOrderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_order_id: Option<Option<String>>,
    #[serde(rename = "shippingMethodId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_method_id: Option<Option<String>>,
    #[serde(rename = "billingLocationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billing_location_id: Option<Option<String>>,
    #[serde(rename = "shippingLocationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_location_id: Option<Option<String>>,
    #[serde(rename = "qualifiedIdentifier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qualified_identifier: Option<Option<String>>,
    #[serde(rename = "costCalculationMethod", skip_serializing_if = "Option::is_none")]
    pub cost_calculation_method: Option<CostCalculationMethod>,
    #[serde(rename = "freightTerms", skip_serializing_if = "Option::is_none")]
    pub freight_terms: Option<FreightTerms>,
    #[serde(rename = "orderStatus", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<OrderStatus>,
    #[serde(rename = "requestedDeliveryDate", skip_serializing_if = "Option::is_none")]
    pub requested_delivery_date: Option<String>,
    #[serde(rename = "customTaxAmount", skip_serializing_if = "Option::is_none")]
    pub custom_tax_amount: Option<f64>,
    #[serde(rename = "customTotalAmount", skip_serializing_if = "Option::is_none")]
    pub custom_total_amount: Option<f64>,
    #[serde(rename = "customDetailAmount", skip_serializing_if = "Option::is_none")]
    pub custom_detail_amount: Option<f64>,
    #[serde(rename = "customProfitAmount", skip_serializing_if = "Option::is_none")]
    pub custom_profit_amount: Option<f64>,
    #[serde(rename = "customDiscountsAmount", skip_serializing_if = "Option::is_none")]
    pub custom_discounts_amount: Option<f64>,
    #[serde(rename = "customSurchargesAmount", skip_serializing_if = "Option::is_none")]
    pub custom_surcharges_amount: Option<f64>,
    #[serde(rename = "customShippingTaxAmount", skip_serializing_if = "Option::is_none")]
    pub custom_shipping_tax_amount: Option<f64>,
    #[serde(rename = "customShippingCostAmount", skip_serializing_if = "Option::is_none")]
    pub custom_shipping_cost_amount: Option<f64>,
    #[serde(rename = "customWithholdingTaxAmount", skip_serializing_if = "Option::is_none")]
    pub custom_withholding_tax_amount: Option<f64>,
}

impl OrderDto {
    pub fn new() -> OrderDto {
        OrderDto {
            id: None,
            timestamp: None,
            closed: None,
            r#type: None,
            title: None,
            user_id: None,
            tenant_id: None,
            description: None,
            price_list_id: None,
            enrollment_id: None,
            individual_id: None,
            organization_id: None,
            receiver_tenant_id: None,
            first_name: None,
            last_name: None,
            company_name: None,
            billing_email: None,
            address_line1: None,
            address_line2: None,
            postal_code: None,
            country_id: None,
            state_id: None,
            city_id: None,
            customer_notes: None,
            tax_calculation_method: None,
            forex_rate: None,
            currency_id: None,
            total_detail: None,
            total_detail_currency_id: None,
            total_profit: None,
            total_profit_currency_id: None,
            total_discounts: None,
            total_discounts_currency_id: None,
            total_surcharges: None,
            total_surcharges_currency_id: None,
            total_tax_base: None,
            total_tax_base_currency_id: None,
            total_taxes: None,
            total_taxes_currency_id: None,
            total_shipping_cost: None,
            total_shipping_cost_currency_id: None,
            total_shipping_tax: None,
            total_shipping_tax_currency_id: None,
            total_withheld_tax: None,
            total_withheld_tax_currency_id: None,
            total_global_discounts: None,
            total_global_discounts_currency_id: None,
            total_global_surcharges: None,
            total_global_surcharges_currency_id: None,
            total: None,
            total_currency_id: None,
            total_detail_in_usd: None,
            total_profit_in_usd: None,
            total_discounts_in_usd: None,
            total_surcharges_in_usd: None,
            total_tax_base_in_usd: None,
            total_taxes_in_usd: None,
            total_withheld_taxes_in_usd: None,
            total_shipping_cost_in_usd: None,
            total_shipping_taxes_in_usd: None,
            total_global_discounts_in_usd: None,
            total_global_surcharges_in_usd: None,
            total_in_usd: None,
            order_lines_count: None,
            quote_id: None,
            wallet_id: None,
            payment_term_id: None,
            parent_order_id: None,
            shipping_method_id: None,
            billing_location_id: None,
            shipping_location_id: None,
            qualified_identifier: None,
            cost_calculation_method: None,
            freight_terms: None,
            order_status: None,
            requested_delivery_date: None,
            custom_tax_amount: None,
            custom_total_amount: None,
            custom_detail_amount: None,
            custom_profit_amount: None,
            custom_discounts_amount: None,
            custom_surcharges_amount: None,
            custom_shipping_tax_amount: None,
            custom_shipping_cost_amount: None,
            custom_withholding_tax_amount: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaxCalculationMethod {
    #[serde(rename = "Included")]
    Included,
    #[serde(rename = "Excluded")]
    Excluded,
}

impl Default for TaxCalculationMethod {
    fn default() -> TaxCalculationMethod {
        Self::Included
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CostCalculationMethod {
    #[serde(rename = "Automatic")]
    Automatic,
    #[serde(rename = "Custom")]
    Custom,
}

impl Default for CostCalculationMethod {
    fn default() -> CostCalculationMethod {
        Self::Automatic
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FreightTerms {
    #[serde(rename = "FOB")]
    Fob,
    #[serde(rename = "NoCharge")]
    NoCharge,
}

impl Default for FreightTerms {
    fn default() -> FreightTerms {
        Self::Fob
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "New")]
    New,
    #[serde(rename = "Processing")]
    Processing,
    #[serde(rename = "Accepted")]
    Accepted,
    #[serde(rename = "Declined")]
    Declined,
    #[serde(rename = "Shipped")]
    Shipped,
    #[serde(rename = "Delivered")]
    Delivered,
    #[serde(rename = "OnHold")]
    OnHold,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Fulfilled")]
    Fulfilled,
    #[serde(rename = "Cancelled")]
    Cancelled,
}

impl Default for OrderStatus {
    fn default() -> OrderStatus {
        Self::New
    }
}

