/*
 * WalletsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletWithdrawRequestDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "requestedWithdrawAmount", skip_serializing_if = "Option::is_none")]
    pub requested_withdraw_amount: Option<f64>,
    #[serde(rename = "requestedWithdrawAmountInUSD", skip_serializing_if = "Option::is_none")]
    pub requested_withdraw_amount_in_usd: Option<f64>,
    #[serde(rename = "walletWithdrawRequestStatus", skip_serializing_if = "Option::is_none")]
    pub wallet_withdraw_request_status: Option<WalletWithdrawRequestStatus>,
    #[serde(rename = "currencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Option<String>>,
    #[serde(rename = "businessId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_id: Option<Option<String>>,
    #[serde(rename = "walletAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet_account_id: Option<Option<String>>,
    #[serde(rename = "bankAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_account_id: Option<Option<String>>,
}

impl WalletWithdrawRequestDto {
    pub fn new() -> WalletWithdrawRequestDto {
        WalletWithdrawRequestDto {
            id: None,
            timestamp: None,
            requested_withdraw_amount: None,
            requested_withdraw_amount_in_usd: None,
            wallet_withdraw_request_status: None,
            currency_id: None,
            business_id: None,
            wallet_account_id: None,
            bank_account_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletWithdrawRequestStatus {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Processed")]
    Processed,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "OnHold")]
    OnHold,
    #[serde(rename = "Denied")]
    Denied,
}

impl Default for WalletWithdrawRequestStatus {
    fn default() -> WalletWithdrawRequestStatus {
        Self::Pending
    }
}

