/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimsPrincipal {
    #[serde(rename = "claims", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub claims: Option<Option<Vec<models::Claim>>>,
    #[serde(rename = "identities", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub identities: Option<Option<Vec<models::ClaimsIdentity>>>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::IIdentity>>,
}

impl ClaimsPrincipal {
    pub fn new() -> ClaimsPrincipal {
        ClaimsPrincipal {
            claims: None,
            identities: None,
            identity: None,
        }
    }
}

