/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpAddress {
    #[serde(rename = "addressFamily", skip_serializing_if = "Option::is_none")]
    pub address_family: Option<AddressFamily>,
    #[serde(rename = "scopeId", skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<i64>,
    #[serde(rename = "isIPv6Multicast", skip_serializing_if = "Option::is_none")]
    pub is_ipv6_multicast: Option<bool>,
    #[serde(rename = "isIPv6LinkLocal", skip_serializing_if = "Option::is_none")]
    pub is_ipv6_link_local: Option<bool>,
    #[serde(rename = "isIPv6SiteLocal", skip_serializing_if = "Option::is_none")]
    pub is_ipv6_site_local: Option<bool>,
    #[serde(rename = "isIPv6Teredo", skip_serializing_if = "Option::is_none")]
    pub is_ipv6_teredo: Option<bool>,
    #[serde(rename = "isIPv6UniqueLocal", skip_serializing_if = "Option::is_none")]
    pub is_ipv6_unique_local: Option<bool>,
    #[serde(rename = "isIPv4MappedToIPv6", skip_serializing_if = "Option::is_none")]
    pub is_ipv4_mapped_to_ipv6: Option<bool>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<i64>,
}

impl IpAddress {
    pub fn new() -> IpAddress {
        IpAddress {
            address_family: None,
            scope_id: None,
            is_ipv6_multicast: None,
            is_ipv6_link_local: None,
            is_ipv6_site_local: None,
            is_ipv6_teredo: None,
            is_ipv6_unique_local: None,
            is_ipv4_mapped_to_ipv6: None,
            address: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressFamily {
    #[serde(rename = "Unspecified")]
    Unspecified,
    #[serde(rename = "Unix")]
    Unix,
    #[serde(rename = "InterNetwork")]
    InterNetwork,
    #[serde(rename = "ImpLink")]
    ImpLink,
    #[serde(rename = "Pup")]
    Pup,
    #[serde(rename = "Chaos")]
    Chaos,
    #[serde(rename = "NS")]
    Ns,
    #[serde(rename = "Iso")]
    Iso,
    #[serde(rename = "Ecma")]
    Ecma,
    #[serde(rename = "DataKit")]
    DataKit,
    #[serde(rename = "Ccitt")]
    Ccitt,
    #[serde(rename = "Sna")]
    Sna,
    #[serde(rename = "DecNet")]
    DecNet,
    #[serde(rename = "DataLink")]
    DataLink,
    #[serde(rename = "Lat")]
    Lat,
    #[serde(rename = "HyperChannel")]
    HyperChannel,
    #[serde(rename = "AppleTalk")]
    AppleTalk,
    #[serde(rename = "NetBios")]
    NetBios,
    #[serde(rename = "VoiceView")]
    VoiceView,
    #[serde(rename = "FireFox")]
    FireFox,
    #[serde(rename = "Banyan")]
    Banyan,
    #[serde(rename = "Atm")]
    Atm,
    #[serde(rename = "InterNetworkV6")]
    InterNetworkV6,
    #[serde(rename = "Cluster")]
    Cluster,
    #[serde(rename = "Ieee12844")]
    Ieee12844,
    #[serde(rename = "Irda")]
    Irda,
    #[serde(rename = "NetworkDesigners")]
    NetworkDesigners,
    #[serde(rename = "Max")]
    Max,
    #[serde(rename = "Packet")]
    Packet,
    #[serde(rename = "ControllerAreaNetwork")]
    ControllerAreaNetwork,
    #[serde(rename = "Unknown")]
    Unknown,
}

impl Default for AddressFamily {
    fn default() -> AddressFamily {
        Self::Unspecified
    }
}

