/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MicrosoftIntegrationsOptions {
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "azure", skip_serializing_if = "Option::is_none")]
    pub azure: Option<Box<models::MicrosoftAzureIntegrationOptions>>,
}

impl MicrosoftIntegrationsOptions {
    pub fn new() -> MicrosoftIntegrationsOptions {
        MicrosoftIntegrationsOptions {
            enable: None,
            azure: None,
        }
    }
}

