/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ODataRawQueryOptions {
    #[serde(rename = "filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Option<String>>,
    #[serde(rename = "apply", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub apply: Option<Option<String>>,
    #[serde(rename = "compute", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Option<String>>,
    #[serde(rename = "search", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub search: Option<Option<String>>,
    #[serde(rename = "orderBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_by: Option<Option<String>>,
    #[serde(rename = "top", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub top: Option<Option<String>>,
    #[serde(rename = "skip", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub skip: Option<Option<String>>,
    #[serde(rename = "select", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub select: Option<Option<String>>,
    #[serde(rename = "expand", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expand: Option<Option<String>>,
    #[serde(rename = "count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub count: Option<Option<String>>,
    #[serde(rename = "format", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub format: Option<Option<String>>,
    #[serde(rename = "skipToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub skip_token: Option<Option<String>>,
    #[serde(rename = "deltaToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delta_token: Option<Option<String>>,
}

impl ODataRawQueryOptions {
    pub fn new() -> ODataRawQueryOptions {
        ODataRawQueryOptions {
            filter: None,
            apply: None,
            compute: None,
            search: None,
            order_by: None,
            top: None,
            skip: None,
            select: None,
            expand: None,
            count: None,
            format: None,
            skip_token: None,
            delta_token: None,
        }
    }
}

