/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortalSettings {
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    #[serde(rename = "portalID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub portal_id: Option<Option<String>>,
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<String>>,
    #[serde(rename = "tenantID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "homePageID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub home_page_id: Option<Option<String>>,
    #[serde(rename = "blogPageID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub blog_page_id: Option<Option<String>>,
    #[serde(rename = "storePageID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub store_page_id: Option<Option<String>>,
    #[serde(rename = "baseEndpoint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub base_endpoint: Option<Option<String>>,
    #[serde(rename = "storeRoutePrefix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub store_route_prefix: Option<Option<String>>,
    #[serde(rename = "publicKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Option<String>>,
    #[serde(rename = "privateKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<Option<String>>,
    #[serde(rename = "authToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<Option<String>>,
    #[serde(rename = "authTokenType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_token_type: Option<Option<String>>,
    #[serde(rename = "authTokenExpiration", skip_serializing_if = "Option::is_none")]
    pub auth_token_expiration: Option<i64>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::PortalOptions>>,
}

impl PortalSettings {
    pub fn new() -> PortalSettings {
        PortalSettings {
            enable: None,
            portal_id: None,
            scopes: None,
            tenant_id: None,
            home_page_id: None,
            blog_page_id: None,
            store_page_id: None,
            base_endpoint: None,
            store_route_prefix: None,
            public_key: None,
            private_key: None,
            auth_token: None,
            auth_token_type: None,
            auth_token_expiration: None,
            options: None,
        }
    }
}

