/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebPortalDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<bool>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "enrollmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enrollment_id: Option<Option<String>>,
    #[serde(rename = "websiteThemeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub website_theme_id: Option<Option<String>>,
    #[serde(rename = "businessDomainId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_domain_id: Option<Option<String>>,
    #[serde(rename = "businessPortalApplicationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_portal_application_id: Option<Option<String>>,
}

impl WebPortalDto {
    pub fn new() -> WebPortalDto {
        WebPortalDto {
            id: None,
            timestamp: None,
            root: None,
            title: None,
            domain: None,
            disabled: None,
            tenant_id: None,
            description: None,
            enrollment_id: None,
            website_theme_id: None,
            business_domain_id: None,
            business_portal_application_id: None,
        }
    }
}

