/*
 * LogisticsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RailWaybillUpdateDto {
    #[serde(rename = "documentNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub document_number: Option<Option<String>>,
    #[serde(rename = "shipperContactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipper_contact_id: Option<Option<String>>,
    #[serde(rename = "consigneeContactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub consignee_contact_id: Option<Option<String>>,
    #[serde(rename = "carrierId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub carrier_id: Option<Option<String>>,
    #[serde(rename = "railOperatorName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rail_operator_name: Option<Option<String>>,
    #[serde(rename = "stationOfDeparture", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub station_of_departure: Option<Option<String>>,
    #[serde(rename = "stationOfDepartureCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub station_of_departure_code: Option<Option<String>>,
    #[serde(rename = "stationOfDestination", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub station_of_destination: Option<Option<String>>,
    #[serde(rename = "stationOfDestinationCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub station_of_destination_code: Option<Option<String>>,
    #[serde(rename = "prescribedRoute", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prescribed_route: Option<Option<String>>,
    #[serde(rename = "wagonNumbers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wagon_numbers: Option<Option<String>>,
    #[serde(rename = "dateOfAcceptance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_of_acceptance: Option<Option<String>>,
    #[serde(rename = "dateOfDelivery", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_of_delivery: Option<Option<String>>,
    #[serde(rename = "freightTerms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub freight_terms: Option<Option<String>>,
    #[serde(rename = "freightAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub freight_amount: Option<Option<f64>>,
    #[serde(rename = "freightCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub freight_currency_id: Option<Option<String>>,
    #[serde(rename = "totalGrossWeightKg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_gross_weight_kg: Option<Option<f64>>,
    #[serde(rename = "totalPackages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_packages: Option<Option<i32>>,
    #[serde(rename = "totalVolumeM3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_volume_m3: Option<Option<f64>>,
    #[serde(rename = "customsFormalities", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customs_formalities: Option<Option<String>>,
    #[serde(rename = "specialInstructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub special_instructions: Option<Option<String>>,
    #[serde(rename = "remarks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remarks: Option<Option<String>>,
    #[serde(rename = "shipmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipment_id: Option<Option<String>>,
}

impl RailWaybillUpdateDto {
    pub fn new() -> RailWaybillUpdateDto {
        RailWaybillUpdateDto {
            document_number: None,
            shipper_contact_id: None,
            consignee_contact_id: None,
            carrier_id: None,
            rail_operator_name: None,
            station_of_departure: None,
            station_of_departure_code: None,
            station_of_destination: None,
            station_of_destination_code: None,
            prescribed_route: None,
            wagon_numbers: None,
            date_of_acceptance: None,
            date_of_delivery: None,
            freight_terms: None,
            freight_amount: None,
            freight_currency_id: None,
            total_gross_weight_kg: None,
            total_packages: None,
            total_volume_m3: None,
            customs_formalities: None,
            special_instructions: None,
            remarks: None,
            shipment_id: None,
        }
    }
}

