/*
 * LogisticsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WaybillLineDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "parentDocumentType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_document_type: Option<Option<String>>,
    #[serde(rename = "seawayBillId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seaway_bill_id: Option<Option<String>>,
    #[serde(rename = "airwayBillId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub airway_bill_id: Option<Option<String>>,
    #[serde(rename = "roadWaybillId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub road_waybill_id: Option<Option<String>>,
    #[serde(rename = "railWaybillId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rail_waybill_id: Option<Option<String>>,
    #[serde(rename = "lineNumber", skip_serializing_if = "Option::is_none")]
    pub line_number: Option<i32>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "quantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Option<i32>>,
    #[serde(rename = "grossWeightKg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gross_weight_kg: Option<Option<f64>>,
    #[serde(rename = "volumeM3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub volume_m3: Option<Option<f64>>,
    #[serde(rename = "packageType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_type: Option<Option<String>>,
    #[serde(rename = "lengthCm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub length_cm: Option<Option<f64>>,
    #[serde(rename = "widthCm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width_cm: Option<Option<f64>>,
    #[serde(rename = "heightCm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height_cm: Option<Option<f64>>,
    #[serde(rename = "hsCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hs_code: Option<Option<String>>,
    #[serde(rename = "marksAndNumbers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub marks_and_numbers: Option<Option<String>>,
    #[serde(rename = "declaredValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub declared_value: Option<Option<f64>>,
    #[serde(rename = "declaredValueCurrencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub declared_value_currency_id: Option<Option<String>>,
    #[serde(rename = "sealNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seal_number: Option<Option<String>>,
    #[serde(rename = "containerNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub container_number: Option<Option<String>>,
    #[serde(rename = "chargeableWeightKg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chargeable_weight_kg: Option<Option<f64>>,
    #[serde(rename = "iataRateClass", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iata_rate_class: Option<Option<String>>,
    #[serde(rename = "dangerousGoodsClass", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dangerous_goods_class: Option<Option<String>>,
    #[serde(rename = "unHazmatNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub un_hazmat_number: Option<Option<String>>,
    #[serde(rename = "wagonNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wagon_number: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
}

impl WaybillLineDto {
    pub fn new() -> WaybillLineDto {
        WaybillLineDto {
            id: None,
            timestamp: None,
            parent_document_type: None,
            seaway_bill_id: None,
            airway_bill_id: None,
            road_waybill_id: None,
            rail_waybill_id: None,
            line_number: None,
            description: None,
            quantity: None,
            gross_weight_kg: None,
            volume_m3: None,
            package_type: None,
            length_cm: None,
            width_cm: None,
            height_cm: None,
            hs_code: None,
            marks_and_numbers: None,
            declared_value: None,
            declared_value_currency_id: None,
            seal_number: None,
            container_number: None,
            chargeable_weight_kg: None,
            iata_rate_class: None,
            dangerous_goods_class: None,
            un_hazmat_number: None,
            wagon_number: None,
            tenant_id: None,
        }
    }
}

