/*
 * OrdersService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "qualifiedName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qualified_name: Option<Option<String>>,
    #[serde(rename = "taxId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<Option<String>>,
    #[serde(rename = "about", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub about: Option<Option<String>>,
    #[serde(rename = "walletId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<Option<String>>,
    #[serde(rename = "socialFeedId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_feed_id: Option<Option<String>>,
    #[serde(rename = "businessIndustryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_industry_id: Option<Option<String>>,
    #[serde(rename = "businessSegmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_segment_id: Option<Option<String>>,
    #[serde(rename = "socialProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_id: Option<Option<String>>,
    #[serde(rename = "languageId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_id: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "duns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duns: Option<Option<String>>,
    #[serde(rename = "slogan", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub slogan: Option<Option<String>>,
    #[serde(rename = "legalName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Option<String>>,
    #[serde(rename = "coverUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cover_url: Option<Option<String>>,
    #[serde(rename = "avatarUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<Option<String>>,
    #[serde(rename = "cartId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cart_id: Option<Option<String>>,
    #[serde(rename = "currencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Option<String>>,
    #[serde(rename = "timezoneId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timezone_id: Option<Option<String>>,
    #[serde(rename = "countryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_id: Option<Option<String>>,
    #[serde(rename = "stateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<Option<String>>,
    #[serde(rename = "cityId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city_id: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "webUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub web_url: Option<Option<String>>,
    #[serde(rename = "facebookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub facebook_url: Option<Option<String>>,
    #[serde(rename = "twitterUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub twitter_url: Option<Option<String>>,
    #[serde(rename = "gitHubUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub git_hub_url: Option<Option<String>>,
    #[serde(rename = "linkedInUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub linked_in_url: Option<Option<String>>,
    #[serde(rename = "instagramUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instagram_url: Option<Option<String>>,
    #[serde(rename = "youTubeUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub you_tube_url: Option<Option<String>>,
    #[serde(rename = "whatsAppNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub whats_app_number: Option<Option<String>>,
    #[serde(rename = "supportPhoneNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub support_phone_number: Option<Option<String>>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "businessName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_name: Option<Option<String>>,
    #[serde(rename = "businessLegalName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_legal_name: Option<Option<String>>,
    #[serde(rename = "twitterUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub twitter_username: Option<Option<String>>,
}

impl TenantDto {
    pub fn new() -> TenantDto {
        TenantDto {
            id: None,
            timestamp: None,
            qualified_name: None,
            tax_id: None,
            about: None,
            wallet_id: None,
            social_feed_id: None,
            business_industry_id: None,
            business_segment_id: None,
            social_profile_id: None,
            language_id: None,
            name: None,
            duns: None,
            slogan: None,
            legal_name: None,
            cover_url: None,
            avatar_url: None,
            cart_id: None,
            currency_id: None,
            timezone_id: None,
            country_id: None,
            state_id: None,
            city_id: None,
            email: None,
            phone: None,
            web_url: None,
            facebook_url: None,
            twitter_url: None,
            git_hub_url: None,
            linked_in_url: None,
            instagram_url: None,
            you_tube_url: None,
            whats_app_number: None,
            support_phone_number: None,
            verified: None,
            business_name: None,
            business_legal_name: None,
            twitter_username: None,
        }
    }
}

