/*
 * AccountingService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankAccountDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<bool>,
    #[serde(rename = "frozen", skip_serializing_if = "Option::is_none")]
    pub frozen: Option<bool>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "prefix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<Option<String>>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<f64>,
    #[serde(rename = "currencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Option<String>>,
    #[serde(rename = "accountType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<Option<String>>,
    #[serde(rename = "accountTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_type_id: Option<Option<String>>,
    #[serde(rename = "debitsBalance", skip_serializing_if = "Option::is_none")]
    pub debits_balance: Option<f64>,
    #[serde(rename = "creditsBalance", skip_serializing_if = "Option::is_none")]
    pub credits_balance: Option<f64>,
    #[serde(rename = "parentAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_account_id: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "enrollmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enrollment_id: Option<Option<String>>,
    #[serde(rename = "childrenAccountsCount", skip_serializing_if = "Option::is_none")]
    pub children_accounts_count: Option<i32>,
    #[serde(rename = "accountCategory", skip_serializing_if = "Option::is_none")]
    pub account_category: Option<AccountCategory>,
    #[serde(rename = "balanceAmount", skip_serializing_if = "Option::is_none")]
    pub balance_amount: Option<Box<models::Money>>,
    #[serde(rename = "creditsBalanceAmount", skip_serializing_if = "Option::is_none")]
    pub credits_balance_amount: Option<Box<models::Money>>,
    #[serde(rename = "debitsBalanceAmount", skip_serializing_if = "Option::is_none")]
    pub debits_balance_amount: Option<Box<models::Money>>,
    #[serde(rename = "iban", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iban: Option<Option<String>>,
    #[serde(rename = "swift", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub swift: Option<Option<String>>,
    #[serde(rename = "branchCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch_code: Option<Option<String>>,
    #[serde(rename = "bankAccountNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_account_number: Option<Option<String>>,
    #[serde(rename = "qualifiedName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qualified_name: Option<Option<String>>,
    #[serde(rename = "bankId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_id: Option<Option<String>>,
    #[serde(rename = "bankProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_profile_id: Option<Option<String>>,
}

impl BankAccountDto {
    pub fn new() -> BankAccountDto {
        BankAccountDto {
            id: None,
            timestamp: None,
            group: None,
            frozen: None,
            name: None,
            code: None,
            path: None,
            title: None,
            prefix: None,
            balance: None,
            currency_id: None,
            account_type: None,
            account_type_id: None,
            debits_balance: None,
            credits_balance: None,
            parent_account_id: None,
            tenant_id: None,
            enrollment_id: None,
            children_accounts_count: None,
            account_category: None,
            balance_amount: None,
            credits_balance_amount: None,
            debits_balance_amount: None,
            iban: None,
            swift: None,
            branch_code: None,
            bank_account_number: None,
            qualified_name: None,
            bank_id: None,
            bank_profile_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountCategory {
    #[serde(rename = "Assets")]
    Assets,
    #[serde(rename = "Equity")]
    Equity,
    #[serde(rename = "Revenue")]
    Revenue,
    #[serde(rename = "Expense")]
    Expense,
    #[serde(rename = "Liabilities")]
    Liabilities,
}

impl Default for AccountCategory {
    fn default() -> AccountCategory {
        Self::Assets
    }
}

