/*
 * HrmsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5401
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShiftCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "start")]
    pub start: String,
    #[serde(rename = "end")]
    pub end: String,
    #[serde(rename = "isBreak", skip_serializing_if = "Option::is_none")]
    pub is_break: Option<bool>,
    #[serde(rename = "occustOnMonday", skip_serializing_if = "Option::is_none")]
    pub occust_on_monday: Option<bool>,
    #[serde(rename = "occustOnTuesday", skip_serializing_if = "Option::is_none")]
    pub occust_on_tuesday: Option<bool>,
    #[serde(rename = "occustOnWednesday", skip_serializing_if = "Option::is_none")]
    pub occust_on_wednesday: Option<bool>,
    #[serde(rename = "occustOnThursday", skip_serializing_if = "Option::is_none")]
    pub occust_on_thursday: Option<bool>,
    #[serde(rename = "occustOnFriday", skip_serializing_if = "Option::is_none")]
    pub occust_on_friday: Option<bool>,
    #[serde(rename = "occustOnSaturday", skip_serializing_if = "Option::is_none")]
    pub occust_on_saturday: Option<bool>,
    #[serde(rename = "occustOnSunday", skip_serializing_if = "Option::is_none")]
    pub occust_on_sunday: Option<bool>,
    #[serde(rename = "repeatEvery", skip_serializing_if = "Option::is_none")]
    pub repeat_every: Option<i32>,
    #[serde(rename = "repetitionCriteria", skip_serializing_if = "Option::is_none")]
    pub repetition_criteria: Option<RepetitionCriteria>,
    #[serde(rename = "recurrenceStart", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recurrence_start: Option<Option<String>>,
    #[serde(rename = "recurrenceEnd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recurrence_end: Option<Option<String>>,
    #[serde(rename = "dayOfTheWeek", skip_serializing_if = "Option::is_none")]
    pub day_of_the_week: Option<DayOfTheWeek>,
    #[serde(rename = "scheduleId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedule_id: Option<Option<String>>,
    #[serde(rename = "parentTimeIntervalId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_time_interval_id: Option<Option<String>>,
    #[serde(rename = "employeeProfileId")]
    pub employee_profile_id: String,
}

impl ShiftCreateDto {
    pub fn new(title: String, start: String, end: String, employee_profile_id: String) -> ShiftCreateDto {
        ShiftCreateDto {
            id: None,
            timestamp: None,
            title,
            description: None,
            start,
            end,
            is_break: None,
            occust_on_monday: None,
            occust_on_tuesday: None,
            occust_on_wednesday: None,
            occust_on_thursday: None,
            occust_on_friday: None,
            occust_on_saturday: None,
            occust_on_sunday: None,
            repeat_every: None,
            repetition_criteria: None,
            recurrence_start: None,
            recurrence_end: None,
            day_of_the_week: None,
            schedule_id: None,
            parent_time_interval_id: None,
            employee_profile_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RepetitionCriteria {
    #[serde(rename = "NotRepeat")]
    NotRepeat,
    #[serde(rename = "WorkWeek")]
    WorkWeek,
    #[serde(rename = "Day")]
    Day,
    #[serde(rename = "Month")]
    Month,
    #[serde(rename = "Year")]
    Year,
}

impl Default for RepetitionCriteria {
    fn default() -> RepetitionCriteria {
        Self::NotRepeat
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DayOfTheWeek {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "Sunday")]
    Sunday,
    #[serde(rename = "Monday")]
    Monday,
    #[serde(rename = "Tuesday")]
    Tuesday,
    #[serde(rename = "Wednesday")]
    Wednesday,
    #[serde(rename = "Thursday")]
    Thursday,
    #[serde(rename = "Friday")]
    Friday,
    #[serde(rename = "Saturday")]
    Saturday,
}

impl Default for DayOfTheWeek {
    fn default() -> DayOfTheWeek {
        Self::All
    }
}

