/*
 * IdentityService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonWebKeySet {
    #[serde(rename = "keys", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Option<Vec<models::JsonWebKey>>>,
}

impl JsonWebKeySet {
    pub fn new() -> JsonWebKeySet {
        JsonWebKeySet {
            keys: None,
        }
    }
}

