/*
 * IdentityService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonWebKey {
    #[serde(rename = "kid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kid: Option<Option<String>>,
    #[serde(rename = "nbf", skip_serializing_if = "Option::is_none")]
    pub nbf: Option<i64>,
    #[serde(rename = "use", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#use: Option<Option<String>>,
    #[serde(rename = "kty", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kty: Option<Option<String>>,
    #[serde(rename = "e", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub e: Option<Option<String>>,
    #[serde(rename = "n", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub n: Option<Option<String>>,
}

impl JsonWebKey {
    pub fn new() -> JsonWebKey {
        JsonWebKey {
            kid: None,
            nbf: None,
            r#use: None,
            kty: None,
            e: None,
            n: None,
        }
    }
}

