/*
 * BlockchainsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.2.5532
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainUpdateDto {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "logoUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "difficulty", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub difficulty: Option<Option<i32>>,
}

impl BlockchainUpdateDto {
    pub fn new() -> BlockchainUpdateDto {
        BlockchainUpdateDto {
            name: None,
            logo_url: None,
            description: None,
            difficulty: None,
        }
    }
}

