/*
 * CrmService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleContactDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "qualifiedName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qualified_name: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "publicName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_name: Option<Option<String>>,
    #[serde(rename = "firstName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<Option<String>>,
    #[serde(rename = "lastName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<Option<String>>,
    #[serde(rename = "jobTitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_title: Option<Option<String>>,
    #[serde(rename = "coverUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cover_url: Option<Option<String>>,
    #[serde(rename = "avatarUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<Option<String>>,
    #[serde(rename = "countryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_id: Option<Option<String>>,
    #[serde(rename = "timezoneId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timezone_id: Option<Option<String>>,
    #[serde(rename = "languageId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_id: Option<Option<String>>,
    #[serde(rename = "socialProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_id: Option<Option<String>>,
    #[serde(rename = "webUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub web_url: Option<Option<String>>,
    #[serde(rename = "gitHubUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub git_hub_url: Option<Option<String>>,
    #[serde(rename = "twitchUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub twitch_url: Option<Option<String>>,
    #[serde(rename = "redditUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reddit_url: Option<Option<String>>,
    #[serde(rename = "tikTokUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tik_tok_url: Option<Option<String>>,
    #[serde(rename = "websiteUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<Option<String>>,
    #[serde(rename = "twitterUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub twitter_url: Option<Option<String>>,
    #[serde(rename = "facebookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub facebook_url: Option<Option<String>>,
    #[serde(rename = "youTubeUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub you_tube_url: Option<Option<String>>,
    #[serde(rename = "linkedInUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub linked_in_url: Option<Option<String>>,
    #[serde(rename = "instagramUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instagram_url: Option<Option<String>>,
    #[serde(rename = "githubUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub github_username: Option<Option<String>>,
}

impl SimpleContactDto {
    pub fn new() -> SimpleContactDto {
        SimpleContactDto {
            id: None,
            timestamp: None,
            qualified_name: None,
            tenant_id: None,
            r#type: None,
            email: None,
            phone: None,
            public_name: None,
            first_name: None,
            last_name: None,
            job_title: None,
            cover_url: None,
            avatar_url: None,
            country_id: None,
            timezone_id: None,
            language_id: None,
            social_profile_id: None,
            web_url: None,
            git_hub_url: None,
            twitch_url: None,
            reddit_url: None,
            tik_tok_url: None,
            website_url: None,
            twitter_url: None,
            facebook_url: None,
            you_tube_url: None,
            linked_in_url: None,
            instagram_url: None,
            github_username: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Individual")]
    Individual,
    #[serde(rename = "Organization")]
    Organization,
}

impl Default for Type {
    fn default() -> Type {
        Self::Individual
    }
}

