/*
 * ManufacturingService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkstationUpdateDto {
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "locationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Option<String>>,
}

impl WorkstationUpdateDto {
    pub fn new() -> WorkstationUpdateDto {
        WorkstationUpdateDto {
            code: None,
            r#type: None,
            description: None,
            location_id: None,
        }
    }
}

