/*
 * SupportService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportTicketCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "contactID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<String>>,
    #[serde(rename = "supportTicketTypeID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub support_ticket_type_id: Option<Option<String>>,
    #[serde(rename = "supportEntitlementID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub support_entitlement_id: Option<Option<String>>,
    #[serde(rename = "supportPriorityID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub support_priority_id: Option<Option<String>>,
}

impl SupportTicketCreateDto {
    pub fn new() -> SupportTicketCreateDto {
        SupportTicketCreateDto {
            id: None,
            timestamp: None,
            description: None,
            contact_id: None,
            support_ticket_type_id: None,
            support_entitlement_id: None,
            support_priority_id: None,
        }
    }
}

