/*
 * TrustService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SigningCertificateCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "csr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub csr: Option<Option<String>>,
    #[serde(rename = "publicKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Option<String>>,
    #[serde(rename = "certificateType", skip_serializing_if = "Option::is_none")]
    pub certificate_type: Option<CertificateType>,
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "securityCertificateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub security_certificate_id: Option<Option<String>>,
}

impl SigningCertificateCreateDto {
    pub fn new(title: String, contact_id: String) -> SigningCertificateCreateDto {
        SigningCertificateCreateDto {
            id: None,
            timestamp: None,
            title,
            r#type: None,
            url: None,
            csr: None,
            public_key: None,
            certificate_type: None,
            contact_id,
            security_certificate_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CertificateType {
    #[serde(rename = "AuthSignedCertificate")]
    AuthSignedCertificate,
    #[serde(rename = "SelfSignedCertificate")]
    SelfSignedCertificate,
    #[serde(rename = "AllianceSignedCertificate")]
    AllianceSignedCertificate,
}

impl Default for CertificateType {
    fn default() -> CertificateType {
        Self::AuthSignedCertificate
    }
}

