/*
 * TenantsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessRelationshipUpdateDto {
    #[serde(rename = "childTenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub child_tenant_id: Option<Option<String>>,
    #[serde(rename = "ownershipPercentage", skip_serializing_if = "Option::is_none")]
    pub ownership_percentage: Option<f64>,
}

impl BusinessRelationshipUpdateDto {
    pub fn new() -> BusinessRelationshipUpdateDto {
        BusinessRelationshipUpdateDto {
            child_tenant_id: None,
            ownership_percentage: None,
        }
    }
}

