/*
 * TenantsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantSizeCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "employeeLowRangeValue", skip_serializing_if = "Option::is_none")]
    pub employee_low_range_value: Option<i32>,
    #[serde(rename = "employeeHighRangeValue", skip_serializing_if = "Option::is_none")]
    pub employee_high_range_value: Option<i32>,
}

impl TenantSizeCreateDto {
    pub fn new() -> TenantSizeCreateDto {
        TenantSizeCreateDto {
            id: None,
            timestamp: None,
            name: None,
            employee_low_range_value: None,
            employee_high_range_value: None,
        }
    }
}

