/*
 * AssetsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDepreciationRecordUpdateDto {
    #[serde(rename = "depreciationAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub depreciation_amount: Option<Option<f64>>,
    #[serde(rename = "accumulatedDepreciation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accumulated_depreciation: Option<Option<f64>>,
    #[serde(rename = "bookValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub book_value: Option<Option<f64>>,
    #[serde(rename = "depreciationDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub depreciation_date: Option<Option<String>>,
    #[serde(rename = "year", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub year: Option<Option<i32>>,
    #[serde(rename = "month", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub month: Option<Option<i32>>,
}

impl AssetDepreciationRecordUpdateDto {
    pub fn new() -> AssetDepreciationRecordUpdateDto {
        AssetDepreciationRecordUpdateDto {
            depreciation_amount: None,
            accumulated_depreciation: None,
            book_value: None,
            depreciation_date: None,
            year: None,
            month: None,
        }
    }
}

