/*
 * TimeTrackerService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectHoursApprovalStatusUpdateDto {
    #[serde(rename = "approvalStatus", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<ApprovalStatus>,
    #[serde(rename = "comments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Option<String>>,
}

impl ProjectHoursApprovalStatusUpdateDto {
    pub fn new() -> ProjectHoursApprovalStatusUpdateDto {
        ProjectHoursApprovalStatusUpdateDto {
            approval_status: None,
            comments: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Approved")]
    Approved,
    #[serde(rename = "Rejected")]
    Rejected,
}

impl Default for ApprovalStatus {
    fn default() -> ApprovalStatus {
        Self::Pending
    }
}

