/*
 * PricingService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
    #[serde(rename = "itemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "enrollmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enrollment_id: Option<Option<String>>,
    #[serde(rename = "discountListId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discount_list_id: Option<Option<String>>,
    #[serde(rename = "endQuantity", skip_serializing_if = "Option::is_none")]
    pub end_quantity: Option<f64>,
    #[serde(rename = "beginQuantity", skip_serializing_if = "Option::is_none")]
    pub begin_quantity: Option<f64>,
}

impl DiscountDto {
    pub fn new() -> DiscountDto {
        DiscountDto {
            id: None,
            timestamp: None,
            description: None,
            value: None,
            percent: None,
            item_id: None,
            tenant_id: None,
            enrollment_id: None,
            discount_list_id: None,
            end_quantity: None,
            begin_quantity: None,
        }
    }
}

