/*
 * SupportService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`create_support_request_attachment_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSupportRequestAttachmentAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_support_request_attachment_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSupportRequestAttachmentAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_support_request_attachment_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSupportRequestAttachmentAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_support_request_attachments_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSupportRequestAttachmentsAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_support_request_attachments_count_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSupportRequestAttachmentsCountAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_support_request_attachment_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSupportRequestAttachmentAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}


/// Creates a new support request attachment for the specified tenant.
pub async fn create_support_request_attachment_async(configuration: &configuration::Configuration, tenant_id: &str, api_version: Option<&str>, x_api_version: Option<&str>, support_request_attachment_create_dto: Option<models::SupportRequestAttachmentCreateDto>) -> Result<models::EmptyEnvelope, Error<CreateSupportRequestAttachmentAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&support_request_attachment_create_dto);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<CreateSupportRequestAttachmentAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Deletes a support request attachment by its unique identifier.
pub async fn delete_support_request_attachment_async(configuration: &configuration::Configuration, tenant_id: &str, support_request_attachment_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::EmptyEnvelope, Error<DeleteSupportRequestAttachmentAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments/{supportRequestAttachmentId}", local_var_configuration.base_path, supportRequestAttachmentId=crate::apis::urlencode(support_request_attachment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<DeleteSupportRequestAttachmentAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieves a single support request attachment by its unique identifier.
pub async fn get_support_request_attachment_async(configuration: &configuration::Configuration, tenant_id: &str, support_request_attachment_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::SupportRequestAttachmentDtoEnvelope, Error<GetSupportRequestAttachmentAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments/{supportRequestAttachmentId}", local_var_configuration.base_path, supportRequestAttachmentId=crate::apis::urlencode(support_request_attachment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetSupportRequestAttachmentAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieves a list of support request attachments for the specified tenant with OData query support.
pub async fn get_support_request_attachments_async(configuration: &configuration::Configuration, tenant_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::SupportRequestAttachmentDtoListEnvelope, Error<GetSupportRequestAttachmentsAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetSupportRequestAttachmentsAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns the total count of support request attachments for the specified tenant with OData query support.
pub async fn get_support_request_attachments_count_async(configuration: &configuration::Configuration, tenant_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::Int32Envelope, Error<GetSupportRequestAttachmentsCountAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments/Count", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetSupportRequestAttachmentsCountAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates an existing support request attachment by its unique identifier.
pub async fn update_support_request_attachment_async(configuration: &configuration::Configuration, tenant_id: &str, support_request_attachment_id: &str, api_version: Option<&str>, x_api_version: Option<&str>, support_request_attachment_update_dto: Option<models::SupportRequestAttachmentUpdateDto>) -> Result<models::EmptyEnvelope, Error<UpdateSupportRequestAttachmentAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/SupportService/SupportRequestAttachments/{supportRequestAttachmentId}", local_var_configuration.base_path, supportRequestAttachmentId=crate::apis::urlencode(support_request_attachment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&support_request_attachment_update_dto);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<UpdateSupportRequestAttachmentAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

