/*
 * LocationsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "business", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "fax", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fax: Option<Option<String>>,
    #[serde(rename = "address1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address1: Option<Option<String>>,
    #[serde(rename = "address2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address2: Option<Option<String>>,
    #[serde(rename = "address3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address3: Option<Option<String>>,
    #[serde(rename = "unit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Option<String>>,
    #[serde(rename = "cityId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city_id: Option<Option<String>>,
    #[serde(rename = "stateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<Option<String>>,
    #[serde(rename = "postalCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Option<String>>,
    #[serde(rename = "countryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_id: Option<Option<String>>,
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(rename = "isRoutable", skip_serializing_if = "Option::is_none")]
    pub is_routable: Option<bool>,
    #[serde(rename = "isGlobalPrimary", skip_serializing_if = "Option::is_none")]
    pub is_global_primary: Option<bool>,
    #[serde(rename = "isCountryPrimary", skip_serializing_if = "Option::is_none")]
    pub is_country_primary: Option<bool>,
    #[serde(rename = "canGenerateLabels", skip_serializing_if = "Option::is_none")]
    pub can_generate_labels: Option<bool>,
    #[serde(rename = "isDefaultSenderAddress", skip_serializing_if = "Option::is_none")]
    pub is_default_sender_address: Option<bool>,
    #[serde(rename = "isDefaultReturnAddress", skip_serializing_if = "Option::is_none")]
    pub is_default_return_address: Option<bool>,
    #[serde(rename = "isDefaultSuppingLocation", skip_serializing_if = "Option::is_none")]
    pub is_default_supping_location: Option<bool>,
}

impl LocationDto {
    pub fn new() -> LocationDto {
        LocationDto {
            id: None,
            timestamp: None,
            title: None,
            business: None,
            email: None,
            phone: None,
            fax: None,
            address1: None,
            address2: None,
            address3: None,
            unit: None,
            city_id: None,
            state_id: None,
            postal_code: None,
            country_id: None,
            longitude: None,
            latitude: None,
            is_routable: None,
            is_global_primary: None,
            is_country_primary: None,
            can_generate_labels: None,
            is_default_sender_address: None,
            is_default_return_address: None,
            is_default_supping_location: None,
        }
    }
}

