/*
 * LearningService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseAssignmentDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "instructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Option<String>>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<f64>,
    #[serde(rename = "dueDateTime", skip_serializing_if = "Option::is_none")]
    pub due_date_time: Option<String>,
    #[serde(rename = "courseId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_id: Option<Option<String>>,
    #[serde(rename = "courseUnitId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_unit_id: Option<Option<String>>,
    #[serde(rename = "courseSectionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_section_id: Option<Option<String>>,
    #[serde(rename = "courseCohortId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_cohort_id: Option<Option<String>>,
    #[serde(rename = "courseAssignmentTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_assignment_type_id: Option<Option<String>>,
    #[serde(rename = "asignToAllCohorts", skip_serializing_if = "Option::is_none")]
    pub asign_to_all_cohorts: Option<bool>,
    #[serde(rename = "resources", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    #[serde(rename = "enrollmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enrollment_id: Option<Option<String>>,
}

impl CourseAssignmentDto {
    pub fn new() -> CourseAssignmentDto {
        CourseAssignmentDto {
            id: None,
            timestamp: None,
            title: None,
            description: None,
            instructions: None,
            points: None,
            due_date_time: None,
            course_id: None,
            course_unit_id: None,
            course_section_id: None,
            course_cohort_id: None,
            course_assignment_type_id: None,
            asign_to_all_cohorts: None,
            resources: None,
            tenant_id: None,
            enrollment_id: None,
        }
    }
}

