/*
 * LearningService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseCohortUpdateDto {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "startDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_date_time: Option<Option<String>>,
    #[serde(rename = "endDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date_time: Option<Option<String>>,
    #[serde(rename = "expectedStartDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expected_start_date_time: Option<Option<String>>,
    #[serde(rename = "expectedEndDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expected_end_date_time: Option<Option<String>>,
}

impl CourseCohortUpdateDto {
    pub fn new() -> CourseCohortUpdateDto {
        CourseCohortUpdateDto {
            name: None,
            start_date_time: None,
            end_date_time: None,
            expected_start_date_time: None,
            expected_end_date_time: None,
        }
    }
}

