/*
 * LearningService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourseSectionDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "courseID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub course_id: Option<Option<String>>,
    #[serde(rename = "releaseDateTime", skip_serializing_if = "Option::is_none")]
    pub release_date_time: Option<String>,
    #[serde(rename = "hideFromStudents", skip_serializing_if = "Option::is_none")]
    pub hide_from_students: Option<bool>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
}

impl CourseSectionDto {
    pub fn new() -> CourseSectionDto {
        CourseSectionDto {
            id: None,
            timestamp: None,
            icon: None,
            name: None,
            description: None,
            course_id: None,
            release_date_time: None,
            hide_from_students: None,
            tenant_id: None,
        }
    }
}

