/*
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`create_blog_post_tag_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBlogPostTagAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_blog_post_tag_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteBlogPostTagAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_blog_post_tag_by_id_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlogPostTagByIdAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_blog_post_tags_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlogPostTagsAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_blog_post_tag_async`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateBlogPostTagAsyncError {
    Status403(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}


/// Creates a new blog post tag for the specified tenant.
pub async fn create_blog_post_tag_async(configuration: &configuration::Configuration, tenant_id: &str, api_version: Option<&str>, x_api_version: Option<&str>, blog_post_tag_create_dto: Option<models::BlogPostTagCreateDto>) -> Result<models::EmptyEnvelope, Error<CreateBlogPostTagAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/ContentService/BlogPostTags", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&blog_post_tag_create_dto);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<CreateBlogPostTagAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Deletes a blog post tag for the specified tenant.
pub async fn delete_blog_post_tag_async(configuration: &configuration::Configuration, tenant_id: &str, blog_post_tag_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::EmptyEnvelope, Error<DeleteBlogPostTagAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/ContentService/BlogPostTags/{blogPostTagId}", local_var_configuration.base_path, blogPostTagId=crate::apis::urlencode(blog_post_tag_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<DeleteBlogPostTagAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieves a specific blog post tag by its ID.
pub async fn get_blog_post_tag_by_id_async(configuration: &configuration::Configuration, tenant_id: &str, blog_post_tag_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::BlogPostTagDtoEnvelope, Error<GetBlogPostTagByIdAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/ContentService/BlogPostTags/{blogPostTagId}", local_var_configuration.base_path, blogPostTagId=crate::apis::urlencode(blog_post_tag_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetBlogPostTagByIdAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieves all blog post tags for the specified tenant.
pub async fn get_blog_post_tags_async(configuration: &configuration::Configuration, tenant_id: &str, api_version: Option<&str>, x_api_version: Option<&str>) -> Result<models::BlogPostTagDtoListEnvelope, Error<GetBlogPostTagsAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/ContentService/BlogPostTags", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetBlogPostTagsAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates an existing blog post tag for the specified tenant.
pub async fn update_blog_post_tag_async(configuration: &configuration::Configuration, tenant_id: &str, blog_post_tag_id: &str, api_version: Option<&str>, x_api_version: Option<&str>, blog_post_tag_update_dto: Option<models::BlogPostTagUpdateDto>) -> Result<models::EmptyEnvelope, Error<UpdateBlogPostTagAsyncError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/api/v2/ContentService/BlogPostTags/{blogPostTagId}", local_var_configuration.base_path, blogPostTagId=crate::apis::urlencode(blog_post_tag_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tenantId", &tenant_id.to_string())]);
    if let Some(ref local_var_str) = api_version {
        local_var_req_builder = local_var_req_builder.query(&[("api-version", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_version {
        local_var_req_builder = local_var_req_builder.header("x-api-version", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&blog_post_tag_update_dto);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<UpdateBlogPostTagAsyncError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

