/*
 * IntelligenceService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CognitiveAgentSkillCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "cognitiveSkillId")]
    pub cognitive_skill_id: String,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "configJson", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_json: Option<Option<String>>,
}

impl CognitiveAgentSkillCreateDto {
    pub fn new(cognitive_skill_id: String) -> CognitiveAgentSkillCreateDto {
        CognitiveAgentSkillCreateDto {
            id: None,
            timestamp: None,
            cognitive_skill_id,
            enabled: None,
            config_json: None,
        }
    }
}

