/*
 * IntelligenceService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CognitiveSkillToolDto {
    #[serde(rename = "toolKey")]
    pub tool_key: String,
    #[serde(rename = "configJson", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_json: Option<Option<String>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl CognitiveSkillToolDto {
    pub fn new(tool_key: String) -> CognitiveSkillToolDto {
        CognitiveSkillToolDto {
            tool_key,
            config_json: None,
            enabled: None,
        }
    }
}

