/*
 * GlobeService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountryCallingCodeDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "callingCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calling_code: Option<Option<String>>,
    #[serde(rename = "countryID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_id: Option<Option<String>>,
}

impl CountryCallingCodeDto {
    pub fn new() -> CountryCallingCodeDto {
        CountryCallingCodeDto {
            id: None,
            calling_code: None,
            country_id: None,
        }
    }
}

