/*
 * SocialService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialCommentReactionDto {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    #[serde(rename = "reaction", skip_serializing_if = "Option::is_none")]
    pub reaction: Option<Reaction>,
    #[serde(rename = "reactionValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reaction_value: Option<Option<String>>,
    #[serde(rename = "socialProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_id: Option<Option<String>>,
    #[serde(rename = "socialProfileName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_name: Option<Option<String>>,
    #[serde(rename = "socialProfileAvatarUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_avatar_url: Option<Option<String>>,
    #[serde(rename = "socialProfileType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_profile_type: Option<Option<SocialProfileType>>,
    #[serde(rename = "socialCommentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub social_comment_id: Option<Option<String>>,
}

impl SocialCommentReactionDto {
    pub fn new() -> SocialCommentReactionDto {
        SocialCommentReactionDto {
            id: None,
            timestamp: None,
            reaction: None,
            reaction_value: None,
            social_profile_id: None,
            social_profile_name: None,
            social_profile_avatar_url: None,
            social_profile_type: None,
            social_comment_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reaction {
    #[serde(rename = "Like")]
    Like,
    #[serde(rename = "Happy")]
    Happy,
    #[serde(rename = "HaHa")]
    HaHa,
    #[serde(rename = "Love")]
    Love,
    #[serde(rename = "Sad")]
    Sad,
    #[serde(rename = "Angry")]
    Angry,
    #[serde(rename = "Wow")]
    Wow,
    #[serde(rename = "Afraid")]
    Afraid,
}

impl Default for Reaction {
    fn default() -> Reaction {
        Self::Like
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SocialProfileType {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "Tenant")]
    Tenant,
    #[serde(rename = "Contact")]
    Contact,
}

impl Default for SocialProfileType {
    fn default() -> SocialProfileType {
        Self::User
    }
}

