/*
 * ServicesService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceLevelCreateDto {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "sku", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sku: Option<Option<String>>,
    #[serde(rename = "upc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upc: Option<Option<String>>,
    #[serde(rename = "ean", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ean: Option<Option<String>>,
    #[serde(rename = "mpn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpn: Option<Option<String>>,
    #[serde(rename = "isbn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub isbn: Option<Option<String>>,
    #[serde(rename = "asin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asin: Option<Option<String>>,
    #[serde(rename = "gtin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<Option<String>>,
    #[serde(rename = "skUs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sk_us: Option<Option<String>>,
    #[serde(rename = "upCs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub up_cs: Option<Option<String>>,
    #[serde(rename = "eaNs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ea_ns: Option<Option<String>>,
    #[serde(rename = "part", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub part: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "mpNs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mp_ns: Option<Option<String>>,
    #[serde(rename = "isbNs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub isb_ns: Option<Option<String>>,
    #[serde(rename = "asiNs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asi_ns: Option<Option<String>>,
    #[serde(rename = "gtiNs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gti_ns: Option<Option<String>>,
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    #[serde(rename = "unspsc", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unspsc: Option<Option<String>>,
    #[serde(rename = "unitId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_id: Option<Option<String>>,
    #[serde(rename = "series", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub series: Option<Option<String>>,
    #[serde(rename = "barcode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<Option<String>>,
    #[serde(rename = "unspsCs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unsps_cs: Option<Option<String>>,
    #[serde(rename = "summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Option<String>>,
    #[serde(rename = "brandId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_id: Option<Option<String>>,
    #[serde(rename = "pattern", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<Option<String>>,
    #[serde(rename = "features", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub features: Option<Option<String>>,
    #[serde(rename = "material", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub material: Option<Option<String>>,
    #[serde(rename = "permalink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permalink: Option<Option<String>>,
    #[serde(rename = "brandName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<Option<String>>,
    #[serde(rename = "variations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variations: Option<Option<String>>,
    #[serde(rename = "categories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Option<String>>,
    #[serde(rename = "languageId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_id: Option<Option<String>>,
    #[serde(rename = "itemTypeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_type_id: Option<Option<String>>,
    #[serde(rename = "categoryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Option<String>>,
    #[serde(rename = "currencyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Option<String>>,
    #[serde(rename = "unitGroupId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_group_id: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "ingredients", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ingredients: Option<Option<String>>,
    #[serde(rename = "supplierCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_code: Option<Option<String>>,
    #[serde(rename = "shipsToRules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ships_to_rules: Option<Option<String>>,
    #[serde(rename = "parentItemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_item_id: Option<Option<String>>,
    #[serde(rename = "purchaseNote", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_note: Option<Option<String>>,
    #[serde(rename = "tariffHeading", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tariff_heading: Option<Option<String>>,
    #[serde(rename = "mozaicCoverURL", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mozaic_cover_url: Option<Option<String>>,
    #[serde(rename = "youtubeVideoId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub youtube_video_id: Option<Option<String>>,
    #[serde(rename = "nutritionFacts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nutrition_facts: Option<Option<String>>,
    #[serde(rename = "packageContent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_content: Option<Option<String>>,
    #[serde(rename = "primaryImageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_image_url: Option<Option<String>>,
    #[serde(rename = "googleCategories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub google_categories: Option<Option<String>>,
    #[serde(rename = "shortDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub short_description: Option<Option<String>>,
    #[serde(rename = "supplierProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_profile_id: Option<Option<String>>,
    #[serde(rename = "shippingCountryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_country_id: Option<Option<String>>,
    #[serde(rename = "systemRequirements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub system_requirements: Option<Option<String>>,
    #[serde(rename = "customTaxDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_tax_description: Option<Option<String>>,
    #[serde(rename = "pageCoverBackgroundUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_cover_background_url: Option<Option<String>>,
    #[serde(rename = "officialDescriptionUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub official_description_url: Option<Option<String>>,
    #[serde(rename = "recentlyViewedRecordId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recently_viewed_record_id: Option<Option<String>>,
    #[serde(rename = "primaryGoogleCategoryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_google_category_id: Option<Option<String>>,
    #[serde(rename = "supportedOperatingSystem", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supported_operating_system: Option<Option<String>>,
    #[serde(rename = "primaryGoogleCategoryName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_google_category_name: Option<Option<String>>,
    #[serde(rename = "hot", skip_serializing_if = "Option::is_none")]
    pub hot: Option<bool>,
    #[serde(rename = "onSale", skip_serializing_if = "Option::is_none")]
    pub on_sale: Option<bool>,
    #[serde(rename = "auction", skip_serializing_if = "Option::is_none")]
    pub auction: Option<bool>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "digital", skip_serializing_if = "Option::is_none")]
    pub digital: Option<bool>,
    #[serde(rename = "preSale", skip_serializing_if = "Option::is_none")]
    pub pre_sale: Option<bool>,
    #[serde(rename = "taxable", skip_serializing_if = "Option::is_none")]
    pub taxable: Option<bool>,
    #[serde(rename = "inStock", skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<bool>,
    #[serde(rename = "trending", skip_serializing_if = "Option::is_none")]
    pub trending: Option<bool>,
    #[serde(rename = "featured", skip_serializing_if = "Option::is_none")]
    pub featured: Option<bool>,
    #[serde(rename = "lowStock", skip_serializing_if = "Option::is_none")]
    pub low_stock: Option<bool>,
    #[serde(rename = "published", skip_serializing_if = "Option::is_none")]
    pub published: Option<bool>,
    #[serde(rename = "byRequest", skip_serializing_if = "Option::is_none")]
    pub by_request: Option<bool>,
    #[serde(rename = "onDiscount", skip_serializing_if = "Option::is_none")]
    pub on_discount: Option<bool>,
    #[serde(rename = "isDailyDeal", skip_serializing_if = "Option::is_none")]
    pub is_daily_deal: Option<bool>,
    #[serde(rename = "isNewArrival", skip_serializing_if = "Option::is_none")]
    pub is_new_arrival: Option<bool>,
    #[serde(rename = "isWeeklyDeal", skip_serializing_if = "Option::is_none")]
    pub is_weekly_deal: Option<bool>,
    #[serde(rename = "isBestSeller", skip_serializing_if = "Option::is_none")]
    pub is_best_seller: Option<bool>,
    #[serde(rename = "isMonthlyDeal", skip_serializing_if = "Option::is_none")]
    pub is_monthly_deal: Option<bool>,
    #[serde(rename = "hasVariations", skip_serializing_if = "Option::is_none")]
    pub has_variations: Option<bool>,
    #[serde(rename = "isFixedDiscount", skip_serializing_if = "Option::is_none")]
    pub is_fixed_discount: Option<bool>,
    #[serde(rename = "manageInventory", skip_serializing_if = "Option::is_none")]
    pub manage_inventory: Option<bool>,
    #[serde(rename = "isDealersChoice", skip_serializing_if = "Option::is_none")]
    pub is_dealers_choice: Option<bool>,
    #[serde(rename = "isOfficialChoice", skip_serializing_if = "Option::is_none")]
    pub is_official_choice: Option<bool>,
    #[serde(rename = "validPrimaryImage", skip_serializing_if = "Option::is_none")]
    pub valid_primary_image: Option<bool>,
    #[serde(rename = "isDeadlineDiscount", skip_serializing_if = "Option::is_none")]
    pub is_deadline_discount: Option<bool>,
    #[serde(rename = "taxIncludedInPrice", skip_serializing_if = "Option::is_none")]
    pub tax_included_in_price: Option<bool>,
    #[serde(rename = "displayShowcaseTab", skip_serializing_if = "Option::is_none")]
    pub display_showcase_tab: Option<bool>,
    #[serde(rename = "isProductOfTheWeek", skip_serializing_if = "Option::is_none")]
    pub is_product_of_the_week: Option<bool>,
    #[serde(rename = "isProductOfTheMonth", skip_serializing_if = "Option::is_none")]
    pub is_product_of_the_month: Option<bool>,
    #[serde(rename = "isPercentageDiscount", skip_serializing_if = "Option::is_none")]
    pub is_percentage_discount: Option<bool>,
    #[serde(rename = "displayOnGlobalMozaic", skip_serializing_if = "Option::is_none")]
    pub display_on_global_mozaic: Option<bool>,
    #[serde(rename = "displayOnBrandsMozaic", skip_serializing_if = "Option::is_none")]
    pub display_on_brands_mozaic: Option<bool>,
    #[serde(rename = "disableDefaultPolicies", skip_serializing_if = "Option::is_none")]
    pub disable_default_policies: Option<bool>,
    #[serde(rename = "displayOnCategoryMozaic", skip_serializing_if = "Option::is_none")]
    pub display_on_category_mozaic: Option<bool>,
    #[serde(rename = "displayDescriptionEditor", skip_serializing_if = "Option::is_none")]
    pub display_description_editor: Option<bool>,
    #[serde(rename = "displayShortDescriptionEditor", skip_serializing_if = "Option::is_none")]
    pub display_short_description_editor: Option<bool>,
    #[serde(rename = "displayOnBannerMarketingRotation", skip_serializing_if = "Option::is_none")]
    pub display_on_banner_marketing_rotation: Option<bool>,
    #[serde(rename = "viewsCount", skip_serializing_if = "Option::is_none")]
    pub views_count: Option<i32>,
    #[serde(rename = "reviewsCount", skip_serializing_if = "Option::is_none")]
    pub reviews_count: Option<i32>,
    #[serde(rename = "packagedQuantity", skip_serializing_if = "Option::is_none")]
    pub packaged_quantity: Option<i32>,
    #[serde(rename = "recurrency", skip_serializing_if = "Option::is_none")]
    pub recurrency: Option<f64>,
    #[serde(rename = "currentStock", skip_serializing_if = "Option::is_none")]
    pub current_stock: Option<f64>,
    #[serde(rename = "customTaxValue", skip_serializing_if = "Option::is_none")]
    pub custom_tax_value: Option<f64>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<f64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(rename = "totalTax", skip_serializing_if = "Option::is_none")]
    pub total_tax: Option<f64>,
    #[serde(rename = "finalPrice", skip_serializing_if = "Option::is_none")]
    pub final_price: Option<f64>,
    #[serde(rename = "reviewsAvg", skip_serializing_if = "Option::is_none")]
    pub reviews_avg: Option<f64>,
    #[serde(rename = "paymentCost", skip_serializing_if = "Option::is_none")]
    pub payment_cost: Option<f64>,
    #[serde(rename = "regularPrice", skip_serializing_if = "Option::is_none")]
    pub regular_price: Option<f64>,
    #[serde(rename = "discountPrice", skip_serializing_if = "Option::is_none")]
    pub discount_price: Option<f64>,
    #[serde(rename = "discountAmount", skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<f64>,
    #[serde(rename = "discountPercentage", skip_serializing_if = "Option::is_none")]
    pub discount_percentage: Option<f64>,
    #[serde(rename = "estimatedTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_taxes_in_usd: Option<f64>,
    #[serde(rename = "customTaxPercentage", skip_serializing_if = "Option::is_none")]
    pub custom_tax_percentage: Option<f64>,
    #[serde(rename = "estimatedProfitInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_profit_in_usd: Option<f64>,
    #[serde(rename = "estimatedBasePriceInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_base_price_in_usd: Option<f64>,
    #[serde(rename = "estimatedDiscountsInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_discounts_in_usd: Option<f64>,
    #[serde(rename = "estimatedSurchargesInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_surcharges_in_usd: Option<f64>,
    #[serde(rename = "estimatedPaymentTaxInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_payment_tax_in_usd: Option<f64>,
    #[serde(rename = "estimatedTotalPriceInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_total_price_in_usd: Option<f64>,
    #[serde(rename = "estimatedPaymentCostInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_payment_cost_in_usd: Option<f64>,
    #[serde(rename = "estimatedDealSavingsInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_deal_savings_in_usd: Option<f64>,
    #[serde(rename = "estimatedRegularPriceInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_regular_price_in_usd: Option<f64>,
    #[serde(rename = "estimatedTaxBasePriceInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_tax_base_price_in_usd: Option<f64>,
    #[serde(rename = "estimatedWitholdingTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_witholding_taxes_in_usd: Option<f64>,
    #[serde(rename = "estimatedWithholdingTaxesInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_withholding_taxes_in_usd: Option<f64>,
    #[serde(rename = "estimatedDefaultShippingTaxInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_default_shipping_tax_in_usd: Option<f64>,
    #[serde(rename = "estimatedDefaultShippingCostInUsd", skip_serializing_if = "Option::is_none")]
    pub estimated_default_shipping_cost_in_usd: Option<f64>,
    #[serde(rename = "auctionEnd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auction_end: Option<Option<String>>,
    #[serde(rename = "releaseDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "auctionStart", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auction_start: Option<Option<String>>,
    #[serde(rename = "publishedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub published_date: Option<Option<String>>,
    #[serde(rename = "discountDeadLine", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discount_dead_line: Option<Option<String>>,
    #[serde(rename = "deadlineDiscountDueDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline_discount_due_date: Option<Option<String>>,
    #[serde(rename = "deadlineDiscountFromDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline_discount_from_date: Option<Option<String>>,
    #[serde(rename = "lastFixedPricesUpdateDateTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_fixed_prices_update_date_time: Option<Option<String>>,
    #[serde(rename = "selectedTags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_tags: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedTypes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_types: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedBrands", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_brands: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedCategories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_categories: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedTaxPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_tax_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedPricingRules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_pricing_rules: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedRefundPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_refund_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedReturnPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_return_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedPricingPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_pricing_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedWarrantyPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_warranty_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedShipmentPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_shipment_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedGoogleCategories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_google_categories: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedAttributesOptions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_attributes_options: Option<Option<Vec<String>>>,
    #[serde(rename = "selectedSellingMarginPolicies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selected_selling_margin_policies: Option<Option<Vec<String>>>,
    #[serde(rename = "serviceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Option<String>>,
}

impl ServiceLevelCreateDto {
    pub fn new() -> ServiceLevelCreateDto {
        ServiceLevelCreateDto {
            id: None,
            timestamp: None,
            sku: None,
            upc: None,
            ean: None,
            mpn: None,
            isbn: None,
            asin: None,
            gtin: None,
            sk_us: None,
            up_cs: None,
            ea_ns: None,
            part: None,
            name: None,
            r#type: None,
            mp_ns: None,
            isb_ns: None,
            asi_ns: None,
            gti_ns: None,
            model: None,
            title: None,
            color: None,
            unspsc: None,
            unit_id: None,
            series: None,
            barcode: None,
            unsps_cs: None,
            summary: None,
            brand_id: None,
            pattern: None,
            features: None,
            material: None,
            permalink: None,
            brand_name: None,
            variations: None,
            categories: None,
            language_id: None,
            item_type_id: None,
            category_id: None,
            currency_id: None,
            unit_group_id: None,
            description: None,
            ingredients: None,
            supplier_code: None,
            ships_to_rules: None,
            parent_item_id: None,
            purchase_note: None,
            tariff_heading: None,
            mozaic_cover_url: None,
            youtube_video_id: None,
            nutrition_facts: None,
            package_content: None,
            primary_image_url: None,
            google_categories: None,
            short_description: None,
            supplier_profile_id: None,
            shipping_country_id: None,
            system_requirements: None,
            custom_tax_description: None,
            page_cover_background_url: None,
            official_description_url: None,
            recently_viewed_record_id: None,
            primary_google_category_id: None,
            supported_operating_system: None,
            primary_google_category_name: None,
            hot: None,
            on_sale: None,
            auction: None,
            deleted: None,
            digital: None,
            pre_sale: None,
            taxable: None,
            in_stock: None,
            trending: None,
            featured: None,
            low_stock: None,
            published: None,
            by_request: None,
            on_discount: None,
            is_daily_deal: None,
            is_new_arrival: None,
            is_weekly_deal: None,
            is_best_seller: None,
            is_monthly_deal: None,
            has_variations: None,
            is_fixed_discount: None,
            manage_inventory: None,
            is_dealers_choice: None,
            is_official_choice: None,
            valid_primary_image: None,
            is_deadline_discount: None,
            tax_included_in_price: None,
            display_showcase_tab: None,
            is_product_of_the_week: None,
            is_product_of_the_month: None,
            is_percentage_discount: None,
            display_on_global_mozaic: None,
            display_on_brands_mozaic: None,
            disable_default_policies: None,
            display_on_category_mozaic: None,
            display_description_editor: None,
            display_short_description_editor: None,
            display_on_banner_marketing_rotation: None,
            views_count: None,
            reviews_count: None,
            packaged_quantity: None,
            recurrency: None,
            current_stock: None,
            custom_tax_value: None,
            width: None,
            weight: None,
            length: None,
            height: None,
            total_tax: None,
            final_price: None,
            reviews_avg: None,
            payment_cost: None,
            regular_price: None,
            discount_price: None,
            discount_amount: None,
            discount_percentage: None,
            estimated_taxes_in_usd: None,
            custom_tax_percentage: None,
            estimated_profit_in_usd: None,
            estimated_base_price_in_usd: None,
            estimated_discounts_in_usd: None,
            estimated_surcharges_in_usd: None,
            estimated_payment_tax_in_usd: None,
            estimated_total_price_in_usd: None,
            estimated_payment_cost_in_usd: None,
            estimated_deal_savings_in_usd: None,
            estimated_regular_price_in_usd: None,
            estimated_tax_base_price_in_usd: None,
            estimated_witholding_taxes_in_usd: None,
            estimated_withholding_taxes_in_usd: None,
            estimated_default_shipping_tax_in_usd: None,
            estimated_default_shipping_cost_in_usd: None,
            auction_end: None,
            release_date: None,
            auction_start: None,
            published_date: None,
            discount_dead_line: None,
            deadline_discount_due_date: None,
            deadline_discount_from_date: None,
            last_fixed_prices_update_date_time: None,
            selected_tags: None,
            selected_types: None,
            selected_brands: None,
            selected_categories: None,
            selected_tax_policies: None,
            selected_pricing_rules: None,
            selected_refund_policies: None,
            selected_return_policies: None,
            selected_pricing_policies: None,
            selected_warranty_policies: None,
            selected_shipment_policies: None,
            selected_google_categories: None,
            selected_attributes_options: None,
            selected_selling_margin_policies: None,
            service_id: None,
        }
    }
}

