/*
 * SystemService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutboxMessageDtoEnvelope {
    #[serde(rename = "isSuccess", skip_serializing_if = "Option::is_none")]
    pub is_success: Option<bool>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "correlationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<Option<String>>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "httpStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_status: Option<Option<i32>>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "validationDetails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub validation_details: Option<Option<std::collections::HashMap<String, Vec<String>>>>,
    #[serde(rename = "activityId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub activity_id: Option<Option<String>>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::OutboxMessageDto>>,
}

impl OutboxMessageDtoEnvelope {
    pub fn new() -> OutboxMessageDtoEnvelope {
        OutboxMessageDtoEnvelope {
            is_success: None,
            error_message: None,
            correlation_id: None,
            timestamp: None,
            http_status: None,
            error_code: None,
            validation_details: None,
            activity_id: None,
            result: None,
        }
    }
}

